CREATE TABLE [Common].[DimTime] (
    [ID]                   INT          NOT NULL,
    [Hour24]               INT          NOT NULL,
    [Hour24ShortString]    VARCHAR (2)  NOT NULL,
    [Hour24MinString]      VARCHAR (5)  NOT NULL,
    [Hour24FullString]     VARCHAR (8)  NOT NULL,
    [Hour12]               INT          NOT NULL,
    [Hour12ShortString]    VARCHAR (2)  NOT NULL,
    [Hour12MinString]      VARCHAR (5)  NOT NULL,
    [Hour12FullString]     VARCHAR (8)  NOT NULL,
    [AmPmCode]             INT          NOT NULL,
    [AmPmStringEn]         VARCHAR (2)  NOT NULL,
    [AmPmStringFa]         NVARCHAR (3) NOT NULL,
    [Minute]               INT          NOT NULL,
    [MinuteCode]           INT          NOT NULL,
    [MinuteShortString]    VARCHAR (2)  NOT NULL,
    [MinuteFullString24]   VARCHAR (8)  NOT NULL,
    [MinuteFullString12]   VARCHAR (8)  NOT NULL,
    [HalfHour]             INT          NOT NULL,
    [HalfHourCode]         INT          NOT NULL,
    [HalfHourShortString]  VARCHAR (2)  NOT NULL,
    [HalfHourFullString24] VARCHAR (8)  NOT NULL,
    [HalfHourFullString12] VARCHAR (8)  NOT NULL,
    [Second]               INT          NOT NULL,
    [SecondShortString]    VARCHAR (2)  NOT NULL,
    [FullTimeString24]     VARCHAR (8)  NOT NULL,
    [FullTimeString12]     VARCHAR (8)  NOT NULL,
    [FullTime]             TIME (0)     NULL,
    [FullTimeSecond]       INT          NOT NULL,
    [FullTimeMinute]       INT          NOT NULL,
    CONSTRAINT [PK_dim_Time] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

