CREATE TABLE [MaintranceInstance].[LinkServer_Store] (
    [ID]                                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [BranchRef]                               INT             NOT NULL,
    [LinkServerName]                          NVARCHAR (128)  NOT NULL,
    [LoginRemoteName]                         NVARCHAR (128)  NULL,
    [Product]                                 NVARCHAR (128)  NOT NULL,
    [Provider]                                NVARCHAR (128)  NOT NULL,
    [DataSource]                              NVARCHAR (4000) NULL,
    [Location]                                NVARCHAR (4000) NULL,
    [ProviderString]                          NVARCHAR (4000) NULL,
    [DatabaseDefault]                         NVARCHAR (128)  NULL,
    [ConnectTimeout]                          INT             NULL,
    [QueryTimeout]                            INT             NULL,
    [IsLinked]                                BIT             NOT NULL,
    [IsRemoteLoginEnabled]                    BIT             NOT NULL,
    [IsRpcOutEnabled]                         BIT             NOT NULL,
    [IsDataAccessEnabled]                     BIT             NOT NULL,
    [IsCollationCompatible]                   BIT             NOT NULL,
    [UsesRemoteCollation]                     BIT             NOT NULL,
    [CollationName]                           NVARCHAR (128)  NULL,
    [LazySchemaValidation]                    BIT             NOT NULL,
    [IsSystem]                                BIT             NOT NULL,
    [IsPublisher]                             BIT             NOT NULL,
    [IsSubscriber]                            BIT             NULL,
    [IsDistributor]                           BIT             NULL,
    [IsNonSqlSubscriber]                      BIT             NULL,
    [IsRemoteProcTransactionPromotionEnabled] BIT             NULL,
    [IsRdaServer]                             BIT             NULL,
    [LocalPrincipalId]                        INT             NULL,
    [UsesSelfCredential]                      BIT             NOT NULL,
    [LinkServerModifyDatetime]                DATETIME        NOT NULL,
    [LoginModifyDatetime]                     DATETIME        NOT NULL
);

