CREATE TABLE [MaintranceInstance].[SQLInstance_HQ] (
    [BranchRef]                    INT           NOT NULL,
    [ComputerNamePhysicalNetBIOS]  VARCHAR (128) NOT NULL,
    [MachineName]                  VARCHAR (128) NOT NULL,
    [ServerName]                   VARCHAR (128) NOT NULL,
    [ServiceName]                  VARCHAR (128) NOT NULL,
    [Collation]                    VARCHAR (128) NOT NULL,
    [Edition]                      VARCHAR (128) NOT NULL,
    [VersionDesc]                  VARCHAR (250) NOT NULL,
    [ProductBuild]                 VARCHAR (10)  NULL,
    [ProductLevel]                 VARCHAR (10)  NOT NULL,
    [ProductUpdateLevel]           VARCHAR (50)  NULL,
    [ProductVersion]               VARCHAR (10)  NOT NULL,
    [ErrorLogFileName]             VARCHAR (250) NOT NULL,
    [InstanceDefaultDataPath]      VARCHAR (250) NULL,
    [InstanceDefaultLogPath]       VARCHAR (250) NULL,
    [FilestreamConfiguredLevel]    VARCHAR (5)   NOT NULL,
    [FilestreamEffectiveLevel]     VARCHAR (5)   NOT NULL,
    [FilestreamShareName]          VARCHAR (50)  NOT NULL,
    [IsAdvancedAnalyticsInstalled] BIT           NULL,
    [IsClustered]                  BIT           NOT NULL,
    [IsFullTextInstalled]          BIT           NOT NULL,
    [IsIntegratedSecurityOnly]     BIT           NOT NULL,
    [IsPolybaseInstalled]          BIT           NULL,
    [IsSingleUser]                 BIT           NOT NULL,
    [IsXTPSupported]               BIT           NULL,
    [IsLocalDB]                    BIT           NULL,
    [ProductUpdateReference]       VARCHAR (128) NULL,
    [ResourceLastUpdateDatetime]   DATETIME      NOT NULL,
    [MaxWorkerThreads]             INT           NOT NULL,
    [PriorityBoost]                BIT           NOT NULL,
    [CostThresholdForParallelism]  INT           NOT NULL,
    [MaxDegreeOfParallelism]       INT           NOT NULL,
    [MinServerMemory_MB]           INT           NOT NULL,
    [MaxServerMemory_MB]           INT           NOT NULL,
    [DefaultFillFactor_Percent]    INT           NOT NULL,
    [DefaultTraceEnabled]          BIT           NOT NULL,
    [RemoteAdminConnections]       BIT           NOT NULL,
    [DefaultBackupCompression]     BIT           NOT NULL,
    [DefaultBackupCheckSum]        BIT           NULL,
    [OptimizeForAdHocWorkloads]    BIT           NOT NULL,
    [AgentXPs]                     BIT           NOT NULL,
    [DatabaseMailXPs]              BIT           NOT NULL,
    [SMO_DMOXPs]                   BIT           NOT NULL,
    [OleAutomationProcedures]      BIT           NOT NULL,
    [XPCmdShell]                   BIT           NOT NULL,
    [ClrEnabled]                   BIT           NOT NULL,
    [RemoteProcTrans]              INT           NOT NULL,
    [C2AuditMode]                  BIT           NOT NULL,
    [QueryGovernorCostLimit]       INT           NOT NULL,
    [ExternalScriptsEnabled]       BIT           NULL
);

