CREATE TABLE [MaintranceInstance].[SQLInstance] (
    [ID]                                              BIGINT        IDENTITY (1, 1) NOT NULL,
    [Common_BranchRef]                                INT           NOT NULL,
    [ComputerNamePhysicalNetBIOS]                     VARCHAR (128) NOT NULL,
    [MachineName]                                     VARCHAR (128) NOT NULL,
    [ServerName]                                      VARCHAR (128) NOT NULL,
    [ServiceName]                                     VARCHAR (128) NOT NULL,
    [MaintranceDatabase_DatabseCollationRef]          INT           NOT NULL,
    [MaintranceInstance_EditionRef]                   INT           NOT NULL,
    [MaintranceInstance_ProductBuildRef]              INT           NOT NULL,
    [MaintranceInstance_ProductLevelRef]              INT           NOT NULL,
    [MaintranceInstance_ProductUpdateLevelRef]        INT           NOT NULL,
    [MaintranceInstance_ProductVersionRef]            INT           NOT NULL,
    [MaintranceInstance_FilestreamConfiguredLevelRef] INT           NOT NULL,
    [VersionDesc]                                     VARCHAR (250) NOT NULL,
    [ProductVersion]                                  VARCHAR (10)  NOT NULL,
    [ErrorLogFileName]                                VARCHAR (250) NOT NULL,
    [InstanceDefaultDataPath]                         VARCHAR (250) NULL,
    [InstanceDefaultLogPath]                          VARCHAR (250) NULL,
    [FilestreamEffectiveLevel]                        VARCHAR (5)   NOT NULL,
    [FilestreamShareName]                             VARCHAR (50)  NOT NULL,
    [IsAdvancedAnalyticsInstalled]                    BIT           NULL,
    [IsClustered]                                     BIT           NOT NULL,
    [IsFullTextInstalled]                             BIT           NOT NULL,
    [IsIntegratedSecurityOnly]                        BIT           NOT NULL,
    [IsPolybaseInstalled]                             BIT           NULL,
    [IsSingleUser]                                    BIT           NOT NULL,
    [IsXTPSupported]                                  BIT           NULL,
    [IsLocalDB]                                       BIT           NULL,
    [ProductUpdateReference]                          VARCHAR (128) NULL,
    [ResourceLastUpdateDatetime]                      DATETIME      NOT NULL,
    [MaxWorkerThreads]                                INT           NOT NULL,
    [CostThresholdForParallelism]                     INT           NOT NULL,
    [MaxDegreeOfParallelism]                          INT           NOT NULL,
    [MinServerMemoryMB]                               INT           NOT NULL,
    [MaxServerMemoryMB]                               INT           NOT NULL,
    [DefaultFillFactor_Percent]                       INT           NOT NULL,
    [IsPriorityBoost]                                 BIT           NOT NULL,
    [IsDefaultTraceEnabled]                           BIT           NOT NULL,
    [IsRemoteAdminConnections]                        BIT           NOT NULL,
    [IsDefaultBackupCompression]                      BIT           NOT NULL,
    [IsDefaultBackupCheckSum]                         BIT           NULL,
    [IsOptimizeForAdHocWorkloads]                     BIT           NOT NULL,
    [IsAgentXPs]                                      BIT           NOT NULL,
    [IsDatabaseMailXPs]                               BIT           NOT NULL,
    [IsSMODMOXPs]                                     BIT           NOT NULL,
    [IsOleAutomationProcedures]                       BIT           NOT NULL,
    [IsXPCmdShell]                                    BIT           NOT NULL,
    [IsClrEnabled]                                    BIT           NOT NULL,
    [RemoteProcTrans]                                 INT           NOT NULL,
    [IsC2AuditMode]                                   BIT           NOT NULL,
    [IsExternalScriptsEnabled]                        BIT           NULL,
    [QueryGovernorCostLimit]                          INT           NOT NULL,
    [InsertDatetime]                                  DATETIME      NULL,
    CONSTRAINT [PK_MaintranceInstance_SQLInstance] PRIMARY KEY NONCLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90) ON [FG_Data],
    CONSTRAINT [FK_SQLInstance_Branch] FOREIGN KEY ([Common_BranchRef]) REFERENCES [Common].[Branch] ([ID]),
    CONSTRAINT [FK_SQLInstance_DatabseCollation] FOREIGN KEY ([MaintranceDatabase_DatabseCollationRef]) REFERENCES [MaintranceDatabase].[DatabseCollation] ([ID]),
    CONSTRAINT [FK_SQLInstance_Edition] FOREIGN KEY ([MaintranceInstance_EditionRef]) REFERENCES [MaintranceInstance].[Edition] ([ID]),
    CONSTRAINT [FK_SQLInstance_FilestreamConfiguredLevel] FOREIGN KEY ([MaintranceInstance_FilestreamConfiguredLevelRef]) REFERENCES [MaintranceInstance].[FilestreamConfiguredLevel] ([ID]),
    CONSTRAINT [FK_SQLInstance_ProductBuild] FOREIGN KEY ([MaintranceInstance_ProductBuildRef]) REFERENCES [MaintranceInstance].[ProductBuild] ([ID]),
    CONSTRAINT [FK_SQLInstance_ProductLevel] FOREIGN KEY ([MaintranceInstance_ProductLevelRef]) REFERENCES [MaintranceInstance].[ProductLevel] ([ID]),
    CONSTRAINT [FK_SQLInstance_ProductUpdateLevel] FOREIGN KEY ([MaintranceInstance_ProductUpdateLevelRef]) REFERENCES [MaintranceInstance].[ProductUpdateLevel] ([ID]),
    CONSTRAINT [FK_SQLInstance_ProductVersion] FOREIGN KEY ([MaintranceInstance_ProductVersionRef]) REFERENCES [MaintranceInstance].[ProductVersion] ([ID])
) ON [PS_Branch] ([Common_BranchRef]);


GO
ALTER TABLE [MaintranceInstance].[SQLInstance] SET (LOCK_ESCALATION = AUTO);


GO
CREATE CLUSTERED INDEX [IX_MaintranceInstance_SQLInstance]
    ON [MaintranceInstance].[SQLInstance]([ID] ASC, [Common_BranchRef] ASC) WITH (FILLFACTOR = 90, PAD_INDEX = ON)
    ON [PS_Branch] ([Common_BranchRef]);

