CREATE TABLE [MaintranceBackup].[RestoreHistory_HQ] (
    [BranchRef]                    INT            NOT NULL,
    [RestoreDatabase]              NVARCHAR (128) NOT NULL,
    [RestoreUsername]              NVARCHAR (128) NOT NULL,
    [RestoreDatetime]              DATETIME       NOT NULL,
    [BackupSetId]                  INT            NOT NULL,
    [OriginalMachineName]          NVARCHAR (128) NOT NULL,
    [OriginalServerName]           NVARCHAR (128) NOT NULL,
    [OriginalDatabase]             NVARCHAR (128) NOT NULL,
    [OriginalRecoveryModel]        NVARCHAR (60)  NOT NULL,
    [OriginalBackupName]           NVARCHAR (128) NOT NULL,
    [OriginalBackupType]           CHAR (1)       NOT NULL,
    [OriginalFirstLSN]             NUMERIC (25)   NOT NULL,
    [OriginalLastLSN]              NUMERIC (25)   NOT NULL,
    [OriginalCheckpointLSN]        NUMERIC (25)   NOT NULL,
    [OriginalDatabaseBackupLSN]    NUMERIC (25)   NOT NULL,
    [OriginalBackupStartDatetime]  DATETIME       NOT NULL,
    [OriginalBackupFinishDatetime] DATETIME       NOT NULL,
    [OriginalExpirationDate]       DATETIME       NULL,
    [OriginalBackupSize]           NUMERIC (20)   NOT NULL,
    [OriginalCompressedBackupSize] NUMERIC (20)   NOT NULL,
    [OriginalBackupDescription]    NVARCHAR (255) NULL,
    [OriginalIsCopyOnly]           BIT            NOT NULL,
    [OriginalDatabaseVersion]      INT            NOT NULL,
    [IsSingleUser]                 BIT            NOT NULL,
    [IsReadOnly]                   BIT            NOT NULL,
    [HasLastBackupRestoreForDR]    BIT            NOT NULL
);

