CREATE TABLE [Common].[Branch] (
    [ID]                                  INT            IDENTITY (1, 1) NOT NULL,
    [common_BranchTypeRef]                INT            NOT NULL,
    [RegionNo]                            INT            NOT NULL,
    [BranchName]                          NVARCHAR (100) NOT NULL,
    [BranchCode]                          VARCHAR (10)   NOT NULL,
    [BranchNumber]                        VARCHAR (50)   NOT NULL,
    [MachinName]                          VARCHAR (100)  NOT NULL,
    [ServerName]                          VARCHAR (100)  NOT NULL,
    [ServerIP]                            VARCHAR (60)   NOT NULL,
    [Instance]                            VARCHAR (50)   NOT NULL,
    [Port]                                VARCHAR (10)   CONSTRAINT [DF_Branch_Port] DEFAULT ((1433)) NOT NULL,
    [AuthenticationType]                  VARCHAR (10)   CONSTRAINT [DF_common_Barnch_AuthenticationType] DEFAULT ('SQL') NOT NULL,
    [ServerInstance]                      AS             (case when [Instance]='MSSQL' then [ServerName] else concat([ServerName],'\',[Instance],case when [Port]<>'1433' then ','+[Port]  end) end) PERSISTED NOT NULL,
    [ServerIPInstance]                    AS             (case when [Instance]='MSSQL' then [ServerIP] else concat([ServerIP],'\',[Instance],case when [Port]<>'1433' then ','+[Port]  end) end) PERSISTED NOT NULL,
    [Enabled]                             BIT            CONSTRAINT [DF_common_Barnch_Enabled] DEFAULT ((1)) NOT NULL,
    [EnabledAuditLogAction]               BIT            CONSTRAINT [DF_common_Barnch_EnabledAuditLogAction] DEFAULT ((0)) NOT NULL,
    [EnabledBackupset]                    BIT            CONSTRAINT [DF_common_Barnch_EnabledBackupset] DEFAULT ((0)) NOT NULL,
    [EnabledCheckDB]                      BIT            CONSTRAINT [DF_common_Barnch_EnabedChechDB] DEFAULT ((0)) NOT NULL,
    [EnabledDatabases]                    BIT            CONSTRAINT [DF_common_Barnch_EnabedDatabases] DEFAULT ((0)) NOT NULL,
    [EnabledJobActivity]                  BIT            CONSTRAINT [DF_common_Branch_EnabledJobActivity] DEFAULT ((0)) NOT NULL,
    [EnabledJobHistory]                   BIT            CONSTRAINT [DF_common_Barnch_EnabledJobHistory] DEFAULT ((0)) NOT NULL,
    [EnabledRestoreHistory]               BIT            CONSTRAINT [DF_common_Barnch_EnabedRestoreHistory] DEFAULT ((0)) NOT NULL,
    [EnabledReplicationDistributionAgent] BIT            CONSTRAINT [DF_common_Barnch_EnabledReplicationDistributionAgent] DEFAULT ((0)) NOT NULL,
    [EnabledReplicationPublisherLogin]    BIT            CONSTRAINT [DF_common_Barnch_EnabledReplicationPublisherLogin] DEFAULT ((0)) NOT NULL,
    [EnabledReplicationSubscriberLogin]   BIT            CONSTRAINT [DF_common_Barnch_EnabledReplicationSubscriberLogin] DEFAULT ((0)) NOT NULL,
    [EnabledSQLInstance]                  BIT            CONSTRAINT [DF_common_Barnch_EnabledSQLInstance] DEFAULT ((0)) NOT NULL,
    [EnabledSQLService]                   BIT            CONSTRAINT [DF_common_Barnch_EnabledSQLService] DEFAULT ((0)) NOT NULL,
    [EnabledSSISExecution]                BIT            CONSTRAINT [DF_common_Barnch_EnabledSSISExecution] DEFAULT ((0)) NOT NULL,
    [EnabledLinkServer]                   BIT            CONSTRAINT [DF_common_Branch_EnbledLinkServer] DEFAULT ((0)) NOT NULL,
    [EnabledWindowsTime]                  BIT            CONSTRAINT [DF_common_Branch_EnbledWindowsTime] DEFAULT ((0)) NOT NULL,
    [EnabledUpdateRegister]               BIT            CONSTRAINT [DF_common_Barnch_EnabledUpdateRegister] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_common_Branch] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90, PAD_INDEX = ON),
    CONSTRAINT [FK_common_Branch_common_BranchType] FOREIGN KEY ([common_BranchTypeRef]) REFERENCES [Common].[BranchType] ([ID])
);

