CREATE TABLE [MaintranceDatabase].[SQLDatabase_Store] (
    [BranchRef]                    INT            NOT NULL,
    [DatabaseName]                 VARCHAR (50)   NOT NULL,
    [DatabaseLSN]                  NUMERIC (25)   NULL,
    [OwnerSid]                     VARBINARY (85) NULL,
    [OwnerName]                    VARCHAR (250)  NULL,
    [CompatibilityLevel]           TINYINT        NOT NULL,
    [CollationName]                VARCHAR (31)   NOT NULL,
    [CreateDatetime]               DATETIME       NOT NULL,
    [LastGoodCheckDbDatetime]      DATETIME       NULL,
    [UserAccess]                   TINYINT        NOT NULL,
    [UserAccessDesc]               NVARCHAR (60)  NOT NULL,
    [IsReadOnly]                   BIT            NOT NULL,
    [IsAutoCloseOn]                BIT            NOT NULL,
    [IsAutoShrinkOn]               BIT            NOT NULL,
    [RestrictAccess]               TINYINT        NOT NULL,
    [RestrictAccessDesc]           NVARCHAR (60)  NOT NULL,
    [SnapshotIsolationState]       TINYINT        NOT NULL,
    [SnapshotIsolationStateDesc]   NVARCHAR (60)  NOT NULL,
    [IsReadCommittedSnapshotOn]    BIT            NOT NULL,
    [RecoveryModel]                TINYINT        NOT NULL,
    [RecoveryModelDesc]            NVARCHAR (60)  NOT NULL,
    [PageVerifyOption]             TINYINT        NOT NULL,
    [PageVerifyOptionDesc]         NVARCHAR (60)  NOT NULL,
    [IsAutoCreateStatsOn]          BIT            NOT NULL,
    [IsAutoUpdateStatsOn]          BIT            NOT NULL,
    [IsAutoUpdateStatsAsyncOn]     BIT            NOT NULL,
    [IsTrustworthyOn]              BIT            NOT NULL,
    [IsMasterKeyEncryptedByServer] BIT            NOT NULL,
    [IsPublished]                  BIT            NOT NULL,
    [IsSubscribed]                 BIT            NOT NULL,
    [IsDistributor]                BIT            NOT NULL,
    [IsCDCEnabled]                 BIT            NOT NULL,
    [IsEncrypted]                  BIT            NOT NULL
);

